### PR TITLE
[Unicode] Use codecs module to save file

### PR DESCRIPTION
**Pull request by akbargumbira**

### CODE REVIEW

**Comment by michellemoine** [comment]
@akbargumbira, I have made the changes provided to the file leafletFileScripts.py. Qgis2web will not load:

Python error: Couldn't load plugin qgis2web due to an error when calling its classFactory() method See message log (Python Error) for more details.

The log:
2016-02-04T21:14:05	0	QGIS starting...
2016-02-04T21:14:05	0	Python support ENABLED :-) 
2016-02-04T21:14:10	0	Application state:
			QGIS_PREFIX_PATH env var:		C:/PROGRA~1/QGISLY~1/apps/qgis
			Prefix:		C:/PROGRA~1/QGISLY~1/apps/qgis
			Plugin Path:		C:/PROGRA~1/QGISLY~1/apps/qgis/plugins
			Package Data Path:	C:/PROGRA~1/QGISLY~1/apps/qgis/.
			Active Theme Name:	default
			Active Theme Path:	C:/.qgis2///themes\default\icons/
			Default Theme Path:	:/images/themes/default/
			SVG Search Paths:	C:/PROGRA~1/QGISLY~1/apps/qgis/./svg/
					C:/.qgis2//svg/
			User DB Path:	C:/PROGRA~1/QGISLY~1/apps/qgis/./resources/qgis.db
			Auth DB Path:	C:/.qgis2//qgis-auth.db
			
2016-02-04T21:14:10	0	QGIS Ready!

**Comment by michellemoine** [comment]
Sorry, these are the Python errors:

2016-02-04T21:36:26	1	Traceback (most recent call last):
			  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 306, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/.qgis2/python/plugins\qgis2web\__init__.py", line 28, in classFactory
			    from .qgis2web import Qgis2Web
			  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/.qgis2/python/plugins\qgis2web\qgis2web.py", line 25, in <module>
			    from maindialog import MainDialog
			  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/.qgis2/python/plugins\qgis2web\maindialog.py", line 39, in <module>
			    from leafletWriter import *
			  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 30, in <module>
			    from leafletFileScripts import *
			  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/.qgis2/python/plugins\qgis2web\leafletFileScripts.py", line 152
			    base = re.sub('\n[\s_]+\n', '\n', base)
			                                          ^
			IndentationError: unindent does not match any outer indentation level

**Comment by akbargumbira** [comment]
hi, I am sure that you are copy-paste-ing without putting the indentation correctly. You should just copy the file or wait until @tomchadwin merge this to master

**Comment by michellemoine** [comment]
Ok then. Thanks

**Comment by michellemoine** [comment]
The log is displayed as is.

**Comment by michellemoine** [comment]
I just copied the whole file and it's working now. Thank you

**Pull request merged**
