### PR TITLE
Added measure unit options to measure tool

### PR DESCRIPTION
**Pull request by boesiii**
added feet and metric

### CODE REVIEW

**Comment by boesiii** [comment]
One note to add is that this change works for OL3 only.  Still working on leaflet,

**Comment by boesiii** [comment]
Not sure how to fix the travis error.

**Comment by tomchadwin** [comment]
The test failures exist in master, so that's not your code - I need to fix them. The other ones are Python code style, which is what PEP8 is. I can fix them, but you might want o investigate them for the future. It's just a way of standardizing code format.

So, thanks for the PR, and I should be able to get it to merge at some stage.

**Comment by tomchadwin** [comment]
I've finally got Travis happy again, and released 1.5.1. I'll take a look at this when I can and see how it's looking.

**Comment by tomchadwin** [comment]
Finally got round to looking at this. Seems to work well. One thing: the unit is feet even when zoomed way out. The existing metric version switches between m and km according to zoom level. I would have thought that implementing miles would be good. Is this possible?

**Comment by tomchadwin** [comment]
I also don't want "US" as the setting value, as we certainly also use feet. Do you chaps recognize the term "imperial", or is it not used over there?

**Comment by boesiii** [comment]
You are right I should add miles although I am not sure if leaflet was able to have miles also but I will check.

Yes, Imperial would be better to use.

**Comment by tomchadwin** [comment]
I only checked OL3, so if Leaflet only does metres, seems fair to have it only do feet.

**Comment by boesiii** [comment]
Actually Leaflet starts with yards then switches to miles at some point.  I havent figured out how to get leaflet to spit out feet and not yards.

**Comment by tomchadwin** [comment]
Any progress on this? Just checking that you aren't waiting on anything from me.

**Comment by boesiii** [comment]
Changes have been made.  For some reason Leaflet Imperial units are yards and miles.

**Comment by tomchadwin** [comment]
So you're happy with the state of this? I'll have a look at it, and get rid of the PEP8 issues.

**Comment by tomchadwin** [comment]
While I'm happy to tidy up the PEP8 errors, is there any chance you can have a look at the Travis test failures. Those occur because the plugin output does not match the test reference files in https://github.com/tomchadwin/qgis2web/tree/master/test/data/control. Any chance you could have a look at one or two of those, and see where the differences lie?

**Comment by tomchadwin** [comment]
Ah, I think I see what has caused it - not an error. You've added another @VAR@ here:

https://github.com/boesiii/qgis2web/blob/master/resources/qgis2web.js#L218

Although unused in all the existing tests, it's on its own line (correctly). Output from this PR therefore contains one extra blank line in those OL3 tests which compare `qgis2web.js` to controls. I can fix that.

So, I'll try a merge and fixup, and see where that gets us. I'd also like to look into disabling the GUI units control when the measure tool is unselected, though it's not that important.

**Comment by tomchadwin** [comment]
All done and merged - thanks very much for all the work. Very much appreciated!

**Comment by tomchadwin** [comment]
The GUI could be simplified if we took the two checkboxes `Add measure tool` and `Measure tool units`, and replaced them with a single `Measure tool` drop down: "none", "metric", "imperial".

**Comment by boesiii** [comment]
Yes I agree

**Comment by tomchadwin** [comment]
I'm happy to have a go at this, unless you want to do it?

**Comment by tomchadwin** [comment]
Done and committed. Please test.

**Comment by boesiii** [comment]
It works for me!

**Comment by tomchadwin** [comment]
Released as 1.8.0, and uploaded to QGIS plugins repo.

**Pull request merged**
