### PR TITLE
[travis] Install nose-faulthandler

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
I hope that helps to get the nosetests/travis combination to raise a flag on segfaults... Let's see what the test results say.

**Comment by tomchadwin** [comment]
Thanks, @m-kuhn. This will only catch segfaults, though, right? It's Python errors I really want to catch.

**Comment by m-kuhn** [comment]
Yeah, it caused a segfault when I ran it locally on my machine. But that may also be a local setup issue.

See my last mail anyway.

**Comment by m-kuhn** [comment]
That's what I get if I simply type `nosetests`

> QPixmap: Must construct a QApplication before a QPaintDevice
Fatal Python error: Aborted

but no reason to worry if it's no issue for you since it's only a testing issue and not a plugin error.

Maybe you can try to introduce a deliberate error directly in the test script to check if it catches exceptions if they don't pass the Qt machinery between the test script and the place where they get raised.

**Comment by tomchadwin** [comment]
I had that error before when first setting up testing. I'll see if I can figure out why it has resurfaced.

**Pull request merged**
