### PR TITLE
Show build status on github repository

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by tomchadwin** [comment]
Problem with this is that README.md is pulled in as the text of the Help tab in the plugin GUI.

**Comment by m-kuhn** [comment]
Then close without merge ;)

**Comment by tomchadwin** [comment]
No - can you just remove what you added when the text is pulled into the GUI:

https://github.com/tomchadwin/qgis2web/blob/master/maindialog.py#L71

?

**Comment by m-kuhn** [comment]
The only thing that comes to my mind is a sed step as part of the make process or a regex step in python on runtime...

**Comment by tomchadwin** [comment]
I meant the latter, as I don't `make`. Should just be able to regex out that Travis code?

**Comment by m-kuhn** [comment]
Or even easier hardcode removal of the first two lines

**Comment by tomchadwin** [comment]
Yeah, or more, if you add some comments to remind anyone subsequently editing the README.

**Comment by m-kuhn** [comment]
The only question is if the html can be directly set on runtime or if a new copy of the file with processed content needs to be written to the disk somewhere.

**Comment by tomchadwin** [comment]
Yes we can do it at runtime. We can also put a Gitter link in there.

**Comment by tomchadwin** [comment]
We can also add a Gitter link in there:

https://github.com/tomchadwin/qgis2web/pull/165

**Comment by tomchadwin** [comment]
And yes, we can strip it out of the help tab at runtime.

**Comment by tomchadwin** [comment]
See https://github.com/tomchadwin/qgis2web/commit/76ffebe2efdf539374090b1eb4e0eaaa322eb629

Too hacky? Does the job.

**Comment by m-kuhn** [comment]
Does the job :+1:

**Pull request merged**
