### PR TITLE
Mac OS X

### PR DESCRIPTION
**Pull request by jnicho02**
paths for Mac OS X home-brew QGIS 
I also converted the readme to Markdown and plain Englished it

### CODE REVIEW

**Comment by tomchadwin** [comment]
The Help tab of the plugin dialogue uses the README. Can you check it reads markdown?

**Comment by tomchadwin** [comment]
Yeah, it seems a `QTextBrowser` will not read markdown, so I can't merge this. Can you do a PR just for the Mac OS X file?

**Comment by tomchadwin** [comment]
Any chance you can redo the PR, with just the OSX stuff, omitting the README? I can obviously recreate what you did, but if I do, you won't be listed at the committer, and I so like to try to credit people.

**Comment by jnicho02** [comment]
no problem. I've been away in Basel/Germany and OpenDEFRA yesterday

**Comment by tomchadwin** [comment]
Yup, I saw that you've been gadding about. Thanks for this.

**Comment by jnicho02** [comment]
Sometimes I wish I could just leave it alone! but I think that a bit of
text always benefits from a second pair of eyes. And i wanted to include
the scope that you mentioned in the intro at foss4guk

**Pull request closed without merging**
