### PR TITLE
Changed leaflet default crs to epsg 3857 from 4326

### PR DESCRIPTION
**Pull request by boesiii**

### CODE REVIEW

**Comment by boesiii** [comment]
Although if someone changes the precision to a smaller number their data will not look right in Leaflet

**Comment by tomchadwin** [comment]
Well, obviously. The point of the precision setting (as I understand it) is to allow the user to reduce the number of nodes in line/poly layers, thus reducing file size for web download. It obviously therefore makes the data more inaccurate.

**Comment by boesiii** [comment]
Yes but some coordinate systems don't need precision but 4326 does.

1.001 meters versus 1.001 degrees in latitude

**Comment by tomchadwin** [comment]
Assuming this is to be closed and not merged. Reopen if I am wrong.

**Pull request closed without merging**
