### PR TITLE
Typo mistake for fieldAliases parameter

### PR DESCRIPTION
**Pull request by nboisteault**

### CODE REVIEW

**Comment by tomchadwin** [comment]
Thank you! I'll try to fix the tests.

**Comment by tomchadwin** [comment]
Ah, no. It won't let me merge. Are you able to fix the tests? See the Travis log for details.

**Comment by tomchadwin** [comment]
There we go. I *will* sort the tests.

**Comment by nboisteault** [comment]
I didn't understand why tests didn't pass.

**Comment by tomchadwin** [comment]
Because the tests compare the output from the plugin to control files (which are at https://github.com/tomchadwin/qgis2web/tree/master/test/data/control). The control files had the error in them. You fixed the plugin to produce output without the error. It compared it to control files which still had the error, and saw that they didn't match. That is a test fail.

I just updated the test control files with your fix as well, and it all now passes. Thanks again for spotting my mistake and fixing it!

**Comment by nboisteault** [comment]
Understood. You're welcome. Thank you for your great work!

**Pull request merged**
