### PR TITLE
adds "infobox" to leaflet webmaps based on the qgis project abstract

### PR DESCRIPTION
**Pull request by riccardoklinger**
according to issue #762 I've updated the GUI with a new parameter which only supports leaflet writer. No adjustments on test cases so far.

### CODE REVIEW

**Comment by tomchadwin** [comment]
Looks good to me - happy for me to merge?

**Comment by riccardoklinger** [comment]
Hi @tomchadwin , please let me deal with the styling response in issue #762 

I'll do this tonight.

**Comment by riccardoklinger** [comment]
looks much better now : happy to let you merge...
Selection_129
Selection_130

**Comment by tomchadwin** [comment]
OK, I'll test and hopefully merge if all is well (I'm sure it will be). I'd like to investigate how best to give the option *not* to collapse the abstract box, as well, but let's merge and deal with that after.

**Comment by tomchadwin** [comment]
Happy to merge this. I'd like to make a couple of changes before we make a release, though:

- the font in the abstract is different to eg the attribution
- the control (hovered and mouseout) should use the colours defined for widgets in the qgis2web appearance tab

**Comment by riccardoklinger** [comment]
Shall I take care of these proposed changes and create a separate PR?

**Comment by tomchadwin** [comment]
If you are happy to, that would be great - many thanks.

**Pull request merged**
