### PR TITLE
Foss4 guk2016

### PR DESCRIPTION
**Pull request by GeoSpark**
Partial fix for #254

### CODE REVIEW

**Comment by tomchadwin** [comment]
I don't see the merge conflicts. Any idea?

**Comment by tomchadwin** [comment]
Test errors (https://travis-ci.org/tomchadwin/qgis2web/builds/138118887) are only two:

- PEP8, which I can fix after I merge
- fails against 2.8 because that needs to use that deprecated method we saw, so we need to wrap `QgsVectorLayer.editFormConfig()` in a `try:` and fall back to whatever the deprecated method was - again, I can fix that after merging

So we just need to sort the merge conflict. @walkermatt, @volcan01010, any ideas? I'm no good with git.

**Comment by tomchadwin** [comment]
A-ha!

```This branch has no conflicts with the base branch
Merging can be performed automatically. ```

Nice one, @GeoSpark! So it was just the other changes? I thought they didn't conflict. Brilliant!

**Comment by tomchadwin** [comment]
@GeoSpark Are you happy for me to merge?

**Comment by GeoSpark** [comment]
It was a merge conflict with .gitignore which was very odd because I'm the only one who changed it as far as I can tell. *shrugs* I'm cool with the pull, although I've not fixed the PEP8 or the deprecated function call yet. Are you ok to do that or shall I?

**Comment by tomchadwin** [comment]
I'm happy to do it, but say if you want to. I'll merge now anyway, and a new PR can fix those issues. By the way, you must tell me how you figured out what the specific issue was.

**Comment by GeoSpark** [comment]
My docket is rather full having taken off time to come to Southampton, so it will get done sooner if you do it :)

The trick is to use the command line! I set up a second remote repo that points to yours and I called it `parent`:

```
iMac:qgis2web john$ git remote add parent git@github.com:tomchadwin/qgis2web.git
```

Then did a pull into my fork's `FOSS4GUK2016` branch and my computer told me:

```
iMac:qgis2web john$ git pull parent FOSS4GUK2016
From github.com:tomchadwin/qgis2web
 * branch            FOSS4GUK2016 -> FETCH_HEAD
Auto-merging .gitignore
CONFLICT (content): Merge conflict in .gitignore
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by tomchadwin** [comment]
Perfect - thanks for the tip. Doing the test fixes now.

**Pull request merged**
