### PR TITLE
Fix groups and layers representation using QgsLayerTree.

### PR DESCRIPTION
**Pull request by akbargumbira**
This changes means that user needs to have QGIS > 2.4

### CODE REVIEW

**Comment by akbargumbira** [comment]
Hi @tomchadwin, previously for this case i.e I have this structure:
- layer (Potential IDP)
- group (Structure)
-- layer (Road)
-- group (Building)
---layer (Buildings Centroids)
---layer (Buildings)
qgis2

It will throw an error when I click the Preview or Export both for OL and Leaflet. That is because the old code didn't traverse all the layers correctly (Will have the building group as None). Please have a look. I haven't looked though at the execution on exporting and previewing it. It seems that it doesn't work smoothly.

**Comment by tomchadwin** [comment]
I was working on this today, and didn't get as far as you, so let me take a look. Thanks so much for the contribution!

**Comment by tomchadwin** [comment]
OK, it works to populate the layers and groups list in the plugin dialog as it did before. However, it doesn't display the contents of groups, and it places all groups as children of the root node, rather than nesting them. Is that what you see?

**Comment by tomchadwin** [comment]
Oh, and the Travis errors looks as though you have solved most of my problems (with a huge amount of work to the dummy QGIS environment). I'll try to do a PR to correct the actual button clicks in the dialog test to see where that gets us.

**Comment by tomchadwin** [comment]
Do we not have to use root_node.children() instead of root_node.findLayers(), and call it recursively to build up the TreeWidget? That should prevent the flattening of the layers and groups.

**Comment by akbargumbira** [comment]
Yes, it works like the previous behaviour. If you want to have the tree exactly like the legend, probably would be better to use QgsLayerTreeView. It's very simple and with only some lines, you'll get something like this: 
selection_004
I am not sure though if that's what you want

**Comment by tomchadwin** [comment]
I'll have a look at it. If I can add the widgets I need to each layer (visible, popup field, etc), then this might be worth considering.

**Comment by tomchadwin** [comment]
I've now got the group/layer hierarchy right in the UI. Next is to extract it again to send to the export functions. Will branch and commit for this.

**Comment by tomchadwin** [comment]
Branch is here:

https://github.com/tomchadwin/qgis2web/tree/nestedGroups

I now need to figure out what data structures to use to pass the groups and layers to the export functions, as it has fundamentally changed from the previous flat structure. Struggling to visualize a solution at this stage. Perhaps I should just pass the whole TreeWidget, and get rid of some of the other separated out parameters. Actually, that might work rather well.

**Comment by akbargumbira** [comment]
Hmm, what about sending list of layers that are checked by the user? If user only selects one layer and that layer is vector layer, there is another option to choose which attribute to be popped up?

**Comment by tomchadwin** [comment]
That's how it does it now, but that would not preserve the layer/group structure. If I passed in the whole TreeWidget, that by definition would preserve the structure. However, I'd then have to do major rewrites of both OL3 and Leaflet exports, as they currently simply loop through a flat list of layers. I'd have to change this to a nested loop, and build up the same group/layer hierarchy.

There are collateral benefits, however - it would remove the need of the function to extract the values from the GUI, and also remove a lot of variables in the export function calls from the GUI.

This needs further investigation - I've never looked at deep hierarchiy maps in either OL3 of Leaflet, and I don't know how easy they are to code or how well they work. Given that there is a hack in the plugin's Leaflet output code to get it to preserve layer stacking order from QGIS, I wonder if all this is too much work for not enough benefit.

**Pull request merged**
