### PR TITLE
adds interactivity checkbox to layerTree.

### PR DESCRIPTION
**Pull request by riccardoklinger**
This commit adds a new checkbox to the layertree to define a layer as interactive/non-interactive. a non interactive layer is not clickable anymore.
the hidden fields logic just suppresses the showing of the info in the popup an if all fields are defined as hidden, no popup function is defined. yet the layer is still clickable which is misleading. 
An non interactive layer is not clickable anymore so no click event is mitigated and the cursor is not changing to the "click-me" hand.

### CODE REVIEW

**Comment by riccardoklinger** [comment]
sorry for the large number of commits

**Comment by tomchadwin** [comment]
Are you happy with this branch now? Shall I install it, and merge if I'm happy?

**Comment by riccardoklinger** [comment]
Yes, works fine at the moment. So please test and if you like it as well, merge.

**Comment by tomchadwin** [comment]
This looks good in OL, but isn't working for me in Leaflet. Popups still appear when the `Interactive` box is unchecked. I'm using the airports layer in the test folder, all other settings default.

**Comment by riccardoklinger** [comment]
Will check this tonight.

**Comment by riccardoklinger** [comment]
I was able to see the same behaviour. interactivity works on polygons like expected (checked with lake layer). I would assume this to be an leafelt related issue. will dig into it. shall I include an "exception" for point layers?

**Comment by riccardoklinger** [comment]
yes, I will create an issue at github for this. check ths working prototype: https://codepen.io/butcher/pen/dBpWRP

**Comment by riccardoklinger** [comment]
The gis.stackexchange [question for it is posted](https://gis.stackexchange.com/questions/326181/non-interactive-points-in-leaflet). Maybe I am just stupid ;-)

**Comment by riccardoklinger** [comment]
issue is explained. the declaration of non-interactivity needs to be done in the pointToLayer function:
```
function pointToLayer(point, latlng) {
    return L.marker(latlng, {interactive: false});
}
var layer_airports_0 = new L.geoJson(json_airports_0, {
    interactive:false,
    pointToLayer: pointToLayer
}).addTo(map);
```
will push a fix with altered testcases asap... but #helpWanted

**Comment by riccardoklinger** [comment]
Hi @tomchadwinthe interactivity should work now also on point layers in leaflet. please check and merge if wanted.

**Comment by tomchadwin** [comment]
Looking good. One minor cosmetic issue. Can we change the label? "Interactive" isn't very descriptive to me. How about "Popups"?

**Comment by riccardoklinger** [comment]
Yes, sure. Go ahead.

**Comment by tomchadwin** [comment]
Looks good to me. Thanks very much!

**Pull request merged**
