### PR TITLE
More feedback about layers

### PR DESCRIPTION
**Pull request by boesiii**
added feedback message for OL3 and raster layers

### CODE REVIEW

**Comment by tomchadwin** [comment]
Ack. Sorry, @boesiii. We're working on the same thing at the same time... I'll implement your extra changes against my latest ones.

Thanks!

**Comment by boesiii** [comment]
No worries.  Feel free to disregard mine.

**Comment by tomchadwin** [comment]
Thanks. Adding to this feedback thing is strangely satisfying.

**Comment by tomchadwin** [comment]
OK, think I've replicated your changes. Thanks.

**Pull request closed without merging**
