### PR TITLE
Added checkboxes for grouped parent layers

### PR DESCRIPTION
**Pull request by OlaKov**
Hi Tom,

This bit of code allows grouped layers to have their own checkboxes. The children layers’ checkboxes will get disabled (grayed-out) if the parent layer is checked off.

image

 
I’m also making some progress on categorized/graduated layers…I got them to work (on the client-side) by looping through the categorized layers and breaking them down into “sub-layers” based on the categorized criteria. This is my workflow:
1. Loop thought the Json object that contains the layer information e.g. in the airports0.js 
2. Create sub-objects based on the categories.
3. Create new sub-layers using the “sub-json-objects”.
4. Create a new LayerGroup that contains these new categorized layers as `layers`.
5. Modify the `layersList` in the `layers.js`: (1) add the layerGroup to the list; and (2) delete the original categorized layer, because it will cause redundancies.
6. Set which fields are visible (for the popup) below the `var layersList` for each new sub-layer

Old code for the airports layer in the layers.js:

 ```
var format_airports2 = new ol.format.GeoJSON();
 var features_airports2 = format_airports2.readFeatures(json_airports2, 
             {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
 var jsonSource_airports2 = new ol.source.Vector({
     attributions: [new ol.Attribution({html: '<a href=""></a>'})],
 });
 jsonSource_airports2.addFeatures(features_airports2);


 var lyr_airports2 = new ol.layer.Vector({
                 source:jsonSource_airports2, 
                 style: style_airports2,
                 title: 'airports<br />\
         <img src="styles/legend/airports2_0.png" /> Civilian/Public<br />\
         <img src="styles/legend/airports2_1.png" /> Joint Military/Civilian<br />\
         <img src="styles/legend/airports2_2.png" /> Military<br />\
         <img src="styles/legend/airports2_3.png" /> Other<br />'
             });

```

New Code:

```
var cat1_airports2 = [];
var cat2_airports2 = [];
var cat3_airports2 = [];

for (i = 0; i < json_airports2.features.length; i++) {
    var record = json_airports2.features[i]
    if (record.properties.USE == 'Military'){
        cat1_airports2.push(record)
    }else if (record.properties.USE == 'Civilian/Public'){
        cat2_airports2.push(record)
    }else{
        cat3_airports2.push(record)
    }
}

var json_cat1_airports2 = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features":[]};

json_cat1_airports2.features = cat1_airports2;

var json_cat2_airports2 = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features":[]};

json_cat2_airports2.features = cat2_airports2;

var json_cat3_airports2 = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features":[]};

json_cat3_airports2.features = cat3_airports2;

var format_cat1_airports2 = new ol.format.GeoJSON();
var features_cat1_airports2 = format_cat1_airports2.readFeatures(json_cat1_airports2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_cat1_airports2 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});

jsonSource_cat1_airports2.addFeatures(features_cat1_airports2);

var lyr_cat1_airports2 = new ol.layer.Vector({
                source: jsonSource_cat1_airports2, 
                style: style_airports2, //<-- I thi this is fine to leave as is becuase in the styels it checks for categories
                title: '<img src="styles/legend/airports2_2.png" /> Military'
            });

var format_cat2_airports2 = new ol.format.GeoJSON();
var features_cat2_airports2 = format_cat2_airports2.readFeatures(json_cat2_airports2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_cat2_airports2 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});

jsonSource_cat2_airports2.addFeatures(features_cat2_airports2);

var lyr_cat2_airports2 = new ol.layer.Vector({
                source: jsonSource_cat2_airports2, 
                style: style_airports2, //<-- I thi this is fine to leave as is becuase in the styels it checks for categories
                title: '<img src="styles/legend/airports2_0.png" /> Civilian Public'
            });

var format_cat3_airports2 = new ol.format.GeoJSON();
var features_cat3_airports2 = format_cat3_airports2.readFeatures(json_cat3_airports2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_cat3_airports2 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});

jsonSource_cat3_airports2.addFeatures(features_cat3_airports2);

var lyr_cat3_airports2 = new ol.layer.Vector({
                source: jsonSource_cat3_airports2, 
                style: style_airports2, //<-- I thi this is fine to leave as is becuase in the styels it checks for categories
                title: '<img src="styles/legend/airports2_3.png" /> Other'
            });

var airportsGroup = new ol.layer.Group({
    layers: [lyr_cat1_airports2,lyr_cat2_airports2,lyr_cat3_airports2],
    title: 'Alaska Airports'

});
```

I haven’t started with the server-side code yet, thought I’d run this by you first..

### CODE REVIEW

**Comment by tomchadwin** [comment]
The grouped layer bit sounds like a great improvement.  For cat/grad, you are proposing no longer keeping them as single layers and conditionally styling then, instead actually sorting them into different layers?

My main concern is performance. Looping through all features will be a hit. Put it this way: I've had to eliminate as many instances of such loops in the Python, and that's compiled. Looping through in script could be very slow.

Another issue is the layer search. It can only search a single layer.

Sorry to throw potential problems in the way, but we do need to think about them.

**Comment by OlaKov** [comment]
That's ok, we can keep thinking about this. My main argument for splitting the cat/grad layer into  their own layers would be to (1) categories would get clustered together, rather than the whole layer (2) the different categories can get switched on/off in the layer switcher independently. My idea is to split cat/grad into their own layers as early as possible, to save looping-time later on. For example if we keep the categorized layer as a single layer, then to turn off 'Military' airports in the layer-switcher, we would still have to loop through the layer to figure out which features have the 'military' use.  I know you mentioned that you don't want to diverge from the source data too much, so that's why I'm proposing to do it client-side, but I understand that it would slow things down. I haven't used the layer search, and I'm sure there are other obstacles, this is just to get us thinking...

The code I'm commiting is for the layerswitcher, a more accurate representation of what it does is something like this:

image

Right now the layer switcher just gives a title to a group of layers, without adding any new functionality (figure 1). This code allows the parent layer to be turned on/off, as well as the children layers (figure 2, 3). I know there is no easy way for you to test this, but I have a working online version www.okov.ca/test.html.

**Comment by tomchadwin** [comment]
I'll be very happy to merge this in once I get the chance to test it. However, if it stands alone, should you rather make the PR against @walkermatt's layer switcher repo:

https://github.com/walkermatt/ol3-layerswitcher

**Comment by tomchadwin** [comment]
As for layer search, if you/we could implement multi-layer support in that, qgis2web would not be the only beneficiary. It would then allow the method you describe for cat/grad. @ThomasG77's repo is here:

https://github.com/webgeodatavore/ol3-search-layer

**Comment by OlaKov** [comment]
I'm looking at @walkermatt layerswitcher and there seems to be a minor discrepancy:
qgis2web layerswitcher `var lyrId = lyr.get('title').replace(/\s+/g, '-') + '_' + idx;`
walkermatt's layerswitcher `var lyrId = ol.control.LayerSwitcher.uuid();`

Once the layer is assigned an Id in the `renderLayer` function, should it become a part of the layer object so it can be accessed in other places `lyr.S.Id = lyrId`? Right now I'm basically looking up the lyrId using the title, probably not the most efficient way to go, and it doesn't work with walkermatt's version of the code..

**Comment by OlaKov** [comment]
I just removed some unnecessary code with this commit. The code is now compatible with walkermatt's original ol3-layerswitcher, I added lyrId to the layer object as described above. 

I did a pull request in the walkermatt's ol3-layerswitcher repo, do you want me to just cancel this qgis2web pull request?

**Comment by tomchadwin** [comment]
Either this got merged into layerswitcher, or recent discussions over there mean the relevant functionality is hopefully in place or soon to be. Will therefore close, but thanks for the work. Much appreciated.

**Comment by walkermatt** [comment]
@tomchadwin, @OlaKov yes, @dbrnz is currently working on this in https://github.com/walkermatt/ol-layerswitcher/pull/132 👍

**Pull request closed without merging**
