### PR TITLE
Experimental support for MVT layers (OpenLayers only)

### PR DESCRIPTION
**Pull request by HabeltWi**
Hi Tom,
This is an experimental extension of qgis2web supporting vector tile layers as an alternative to GeoJSON files. I've tested it with https://github.com/pka/t-rex
Maybe it's too early for merging, but I think qgis2web could be an interesting base for generating MVT styles from QGIS.
William

### CODE REVIEW

**Comment by tomchadwin** [comment]
I need to understand a lot more about this, as I've never worked with vector tiles before. Tell me if this summary is correct (I'm sure it won't be...):

1. Instead of converting the vectors to GeoJSON, it converts them into vector tiles
2. It exports those tiles to a vector tileserver, whose URL you specify in the GUI

Is that right? If so, I'm going to struggle to test this, as I don't have a readily available vector tile server.

However, this is a genuinely exciting possibility. Things to consider:

1. Can you add Leaflet support? That's pretty much a deal-breaker.
2. Would a better approach not be to identify layers which are already vector tiles in QGIS, and export those as vector tiles in the OL3 and Leaflet output?

Point 2 above adheres to the idea behind qgis2web - don't do anything which something else already does well. Is there a known, usable, and easy process to generate vector tiles from QGIS layers?

Sorry for so many question - I just need to understand this a lot more.

**Comment by HabeltWi** [comment]
Data is not exported at all, because the vector tile server serves them directly from PostGIS. Exporting data to MVT files (usually in mbtiles format) would be interesting for offline use (like e.g. http://osm2vectortiles.org/downloads/).

There already is a Leaflet plugin for vector tiles: https://github.com/SpatialServer/Leaflet.MapboxVectorTile
But I don't know, whether Leaflet JSON styling is also working for vector tiles.

QGIS doesn't support vector tiles as input yet. There is no easy way to create vector tiles from QGIS layers. The mentioned t_rex server does most of the steps for PostGIS layers, but not for other layer types.

The point of this PR is, that there is no tool besides MapBox Studio for styling Vector Tiles. This extension should help alleviate this restriction.

**Comment by tomchadwin** [comment]
> Data is not exported at all

I don't get it. Isn't it exported into the server you specify in the field?

Forgive me - just trying to get a basic understanding. This sounds like it could be terrific.

**Comment by boesiii** [comment]
Not sure how this work either.

This could be an alternative
https://github.com/mapbox/geojson-vt

which I mentioned here
https://github.com/tomchadwin/qgis2web/issues/307

**Comment by pka** [comment]
Here's a digram showing the data flow:
```
                   +-------------+
                   |             |
                +-->    QGIS     |     qgis2web (HTML+Styles)
+------------+  |  |             |  +--------+
|            |  |  +-------------+           |
|   PostGIS  +--+                            v
|            +--+
+------------+  |  +-------------+     +-------------+
                |  | Vector Tile |     |             |
                +--> Server      +-----> OpenLayers  |
                   |             |     |             |
                   +-------------+     +-------------+
```

The current data flow:
```
+------------+     +-------------+
|            |     |             |
|   PostGIS  +----->    QGIS     |
|            |     |             |
+------------+     +-------------+

      +                  +             +-------------+
      |                  |             |             |
      |      qgis2web    +--------->   | OpenLayers  |
      |                                |             |
      |                                +------^------+
      |                                       |
      |                                +------+------+
      |                                |             |
      +---------------------------->   |  GeoJSON    |
                                       |             |
                                       +-------------+
```
@boesiii: geosjson-vt converts GeoJSON, which is not needed as intermediate format in this case. Regarding #307 it would only help, when the conversion is done on server side.

**Comment by tomchadwin** [comment]
Ah! I think I understand now. Thanks, @pka. Let me think about this some more. And let's look at getting the tiles into Leaflet as well. 

Some publically available servers would help us all develop this. Can anyone open up a tileserver and PostGIS instance with such layers?

One thing - the tile server needs to be per layer, not application wide. That will allow heterogeneous layers in one map.

**Comment by tomchadwin** [comment]
> But I don't know, whether Leaflet JSON styling is also working for vector tiles

Looks like it is:

https://github.com/SpatialServer/Leaflet.MapboxVectorTile/blob/master/docs/configuration.md

See `style` config property.

**Comment by tomchadwin** [comment]
Although this was fantastic work, I think other tools have since been developed for styling vector tiles. I'll therefore close this without merging. At the end of the day, qgis2web is meant to export QGIS projects. Since QGIS doesn't natively support vector tiles, the use case is limited.

**Pull request closed without merging**
