### PR TITLE
OL3 basemap attribution #30

### PR DESCRIPTION
**Pull request by lucacasagrande**

### CODE REVIEW

**Comment by tomchadwin** [comment]
I'll try to review this on 4 January. Can you fix the Travis PEP8 issue (a very simple one)

**Comment by lucacasagrande** [comment]
Fixed.

**Comment by tomchadwin** [comment]
Nice. If you've been looking at attributions, I believe sometimes Leaflet shows no qgis2web attribution, perhaps with basemap = None. I've not logged an issue for that yet, as I've not consistently recreated the problem yet.

**Comment by tomchadwin** [comment]
Perfect - many thanks, Luca. Looks spot-on.

**Pull request merged**
