### PR TITLE
Fix tests that use qgis2web.js

### PR DESCRIPTION
**Pull request by OlaKov**
In progress, please don't merge yet!

### CODE REVIEW

**Comment by OlaKov** [comment]
Hi Tom,
The OL3 measure control test keeps failing and I can't figure it out. Maybe I'm not editing the right file or something. It's weird because it doesn't seem to recognize my counter, but it sees when the counter gets incremented. Could you please take a look, I'm not sure how to fix it. Thanks!

**Comment by tomchadwin** [comment]
OK. First, you know you can click on the red X on this page, and it takes you to the test results? Scroll to here:

https://travis-ci.org/tomchadwin/qgis2web/jobs/227509960#L1530

Take the first difference:

`if ( count ==1)`

doesn't match:

`if (count ==1)`

because of the space before "count". The test is literally testing for identical output, including whitespace. Correct that and all the other differences, and it should pass. It can be a frustrating process.

As a shortcut, start a new QGIS project, open ` test/data/layers/airports.shp`. Style it by importing the right style from `test/data/style`. Add a scale bar. Export with qgis2web in OpenLayers format. Open the output folder, and open `resources/qgis2web.js`. Save that as the ol3_measure test control file.

That will only work of you make sure all the other settings remain at their defaults. If it works, do the same for each other falling test. However, they will need you to remove the scalebar, and add in whatever particular feature each test is testing.

**Comment by tomchadwin** [comment]
Nailed it. Congrats, and thanks for all the hard work. Hope it wad of some interest. 

Now we just need @lucacasagrande to fix his PEP8 error and we can release a new version. 

Thanks again - really appreciate the contribution.

**Comment by OlaKov** [comment]
Haha ok! I was just writing you a message about how I think my test files are all fixed, but its still failing. Great, thanks for walking me through my first git!

**Comment by lucacasagrande** [comment]
@tomchadwin where is the error with PEP8?

**Comment by tomchadwin** [comment]
@lucacasagrande Here you go:

https://travis-ci.org/tomchadwin/qgis2web/jobs/227659336#L1337

**Comment by lucacasagrande** [comment]
You are right, sorry. I will fix it!

**Pull request merged**
